apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  nodeSelector:
    jenkins: true
  tolerations:
  - effect: NoSchedule
    key: jenkins
    operator: Equal
    value: true 
  containers:
  - name: jnlp
    workingDir: /home/jenkins
  - name: kaniko
    workingDir: /home/jenkins
    image: public.ecr.aws/d5h017d0/kaniko:latest
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/
    - name: aws-secret
      mountPath: /root/.aws/
  - name: helm
    image: public.ecr.aws/d5h017d0/gitlab-ci:latestv1
    tty: true
  - name: sonarqube
    image: sonarsource/sonar-scanner-cli:4.7
    command: ['/bin/bash']
    tty: true
  restartPolicy: Never
  volumes:
  - name: docker-config
    configMap:
      name: docker-config  
  - name: aws-secret
    secret:
      secretName: aws-secret
